### ISSUE TITLE
Anyone can tell me what is going on here?

### ISSUE THREAD

**Issue by Resonate1** [davidstrauss/google-drive-recursive-ownership#29]
Item b'_Folder for test' needs ownership granted.
    But, current user does not own the item.

That is the point of the script.

**Comment by davidstrauss** [comment]
> That is the point of the script.

No, you can't grant ownership to another user if the user accessing the API lacks ownership of the object in the first place. That's not a limitation of the script; it's a key assumption of the access control model for Google Drive.

The point of the script is to grant/transfer ownership for objects where you have the current ownership.
