### ISSUE TITLE
invalid_clientUnauthorized

### ISSUE THREAD

**Issue by wmclaxton** [davidstrauss/google-drive-recursive-ownership#30]
I am not sure how to modify the client secrets file.  I simply changed the value for "client_secret" to some arbitrary string.  When  I execute the application I am encountering this error.

Changing all files at path "\apardo\non_financial\software_licenses" to owner "abc@gmail.com"
Prefix: ['', 'apardo', 'non_financial', 'software_licenses']
Use this link for authorization: https://accounts.google.com/o/oauth2/auth?clien
t_id=665081966568.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoaut
h%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=
offline&response_type=code
Verification code: 4/tgEQ4-DZTu_acFEc6vUljqjgK8cRrPAhhMLTEIELv_zIsSF_omuEntw
Traceback (most recent call last):
  File "transfer.py", line 133, in <module>
    service = get_drive_service()
  File "transfer.py", line 23, in get_drive_service
    credentials = flow.step2_exchange(code)
  File "C:\utils\python\lib\site-packages\oauth2client\_helpers.py", line 133, i
n positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\utils\python\lib\site-packages\oauth2client\client.py", line 2089, in
 step2_exchange
    raise FlowExchangeError(error_msg)
oauth2client.client.FlowExchangeError: invalid_clientUnauthorized

**Comment by davidstrauss** [comment]
Hi. I've updated [the link for generating client secrets](https://github.com/googleapis/google-api-python-client/blob/master/docs/client-secrets.md). It's something you have to obtain from Google; it's not something you can generate yourself.
