### ISSUE TITLE
Error when changing ownership of pdf files

### ISSUE THREAD

**Issue by coloradotechie** [davidstrauss/google-drive-recursive-ownership#4]
Hi,

On this line in the python code
    return service.permissions().update(fileId=drive_item['id'], permissionId=permission_id, body=permission, transferOwnership=True).execute()

I'm getting this error:
    An error occurred updating ownership permissions: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/randomcharacters/permissions/some_numbers?transferOwnership=true&alt=json returned "Insufficient permissions for this file">

Does the code need to be updated to allow for ownership changes to files that have been uploaded to google drive?

**Comment by davidstrauss** [comment]
Uploaded files should not be any different from documents in the API. Indeed, most of the files I changed ownership for with this script were files, not native Google Docs.

**Comment by jcsahnwaldt** [comment]
I simply can't transfer ownership of a JPEG or PDF, not even through the web interface. I have a standard ("consumer") Google account. What kind of account do you have?

[Google says](http://support.google.com/drive/answer/2494892):

> Google Apps Customers: Only Google Apps customers in Government and Education domains can transfer ownership of a synced or uploaded file (like a PDF or image file). Consumer Drive users: You can't transfer ownership of a synced or uploaded file (like a PDF or an image file).

**Comment by mightyiam** [comment]
This is the reason: ["You can only transfer ownership of Google Docs, Sheets, Slides, or Forms"](https://support.google.com/drive/answer/2494893)

**Comment by Paraka321** [comment]
@mightyiam is correct for general Gmail use. However, G Suite users can use this to transfer ownership of any file type located in Google Drive. This is not a bug, but rather the way Google handles permissions across gmail domains.

**Comment by davidstrauss** [comment]
This is a limitation of the Google Drive product. Several folks here are correct that it's useful to transfer ownership among accounts on a G Suite Google Drive, which is what I originally wrote this for.

**Comment by mightyiam** [comment]
Thank you for following up, @davidstrauss.
