### ISSUE TITLE
wrong owner after script runs

### ISSUE THREAD

**Issue by rainabba** [davidstrauss/google-drive-recursive-ownership#5]
Luckily I caught this early because I have 10,000's of files I was going to execute this on. By comparing the console output and using https://developers.google.com/drive/v2/reference/permissions/getIdForEmail, I can tell that the correct drive#permissionId is being obtained for the email provided in the command-line, but by looking at new owners in drive and activity for affected items, I've found that the wrong account is getting ownership.

I'm forking to investigate and possibly provide some output control options making this hard to use for me. I'll update here and/or submit a PR if I find anything conclusive.

**Comment by davidstrauss** [comment]
Is it assigning the files to a different Google user? Can you provide a concrete example?

**Comment by rainabba** [comment]
My apologies, but I had to work around so I changed my approach with accounts and don't think I can reproduce now. Hopefully this was just a bad perception on my part. If I do run across it again, I will reply here and reopen.
